endpoint: https://apollo-runtime-router-production-4ee8.up.railway.app
operations:
  source: local
  paths:
     - /config/operations

schema:
  source: uplink

transport:
  type: streamable_http
  address: "0.0.0.0"
  port: 5000
